//Project location is defined here
package NHS;

//ALL NEEDED IMPORTS
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class login extends javax.swing.JFrame {

    public static nhs sGP = new nhs();
    public static ArrayList<loginElements> tmpArray = sGP.getArray();

    /**
     * Creates new form loginPage
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBtn1 = new javax.swing.JButton();
        loginBtn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        text2 = new javax.swing.JPasswordField();
        loginTxt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginErrorMsg = new javax.swing.JTextField();

        setTitle("Login");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        loginBtn1.setText("Login");
        loginBtn1.setName("loginBtn1"); // NOI18N
        loginBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn1ActionPerformed(evt);
            }
        });

        loginBtn2.setText("Register");
        loginBtn2.setName("loginBtn2"); // NOI18N
        loginBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Login");

        text2.setName("text2"); // NOI18N

        loginTxt1.setName("userID"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Password");

        loginErrorMsg.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(loginTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(loginErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn2ActionPerformed
        //Creating new JFrame for login form
        register rP = new register();
        //Setting JFrame to visible
        rP.setVisible(true);
    }//GEN-LAST:event_loginBtn2ActionPerformed

    private void loginBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn1ActionPerformed
        //Creating local variables for username and password
        String formUser = loginTxt1.getText(), formPass = new String((text2.getPassword()));

        //Checking of username field is not blank
        if (!formUser.equals("")) {
            //Checking if Password field is not blank
            if (!formPass.equals("")) {
                //Checking of any users are registered 
                if (!sGP.userArray.isEmpty()) {
                    //Loop through the array
                    for (int x = 0; x < tmpArray.size(); x++) {
                        //Comparing all data on array to form data for a succesful login attempt
                        if (formUser.equals(tmpArray.get(x).getUser()) && formPass.equals(tmpArray.get(x).getPassword())) {
                            //Closing login form and opening ip the main class
                            super.dispose();
                            nhs sGP = new nhs();
                            //Parsing username for next main application
                            sGP.activeUser = formUser;
                            sGP.activeUserTxt.setText(formUser);
                            //Loggin the activities by calling a created constructor
                            //Try-Catch statment with IOException used for file handling
                            try {
                                sGP.setLogArray(0);
                            } catch (IOException ex) {
                                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            //Setting main application to visible
                            sGP.setVisible(true);

                            break;
                        } else {
                            //Error Message
                            loginErrorMsg.setText("Incorrect login details!");
                        }
                    }
                } else {
                    //Error Message
                    loginErrorMsg.setText("No account registered!");
                }
            } else {
                //Error Message
                loginErrorMsg.setText("Please fill in the the Password!");
            }
        } else {
            //Error Message
            loginErrorMsg.setText("Please fill in the the Username!");
        }
    }//GEN-LAST:event_loginBtn1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn1;
    private javax.swing.JButton loginBtn2;
    public javax.swing.JTextField loginErrorMsg;
    public javax.swing.JTextField loginTxt1;
    public javax.swing.JPasswordField text2;
    // End of variables declaration//GEN-END:variables
}
