//Project location is defined here
package NHS;

//ALL NEEDED IMPORTS
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

//Class extends JFrame
public class register extends javax.swing.JFrame {

    //Initializing main class and array to check for created accounts
    public static nhs sGP = new nhs();
    public static ArrayList<loginElements> tmpArray = sGP.getArray();

    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        regTxt3 = new javax.swing.JPasswordField();
        regTxt4 = new javax.swing.JPasswordField();
        regTxt2 = new javax.swing.JTextField();
        regTxt1 = new javax.swing.JTextField();
        regBtn = new javax.swing.JButton();
        registerErrorMsg = new javax.swing.JTextField();

        setTitle("Register");
        setBackground(new java.awt.Color(255, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Register");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Repeat Password");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Email");

        regTxt3.setName("text3"); // NOI18N

        regTxt4.setName("text4"); // NOI18N

        regTxt2.setName("text2"); // NOI18N

        regTxt1.setName("text1"); // NOI18N

        regBtn.setText("Register");
        regBtn.setName("btn1"); // NOI18N
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        registerErrorMsg.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(regTxt3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(regTxt2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(regTxt1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(regTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(registerErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        //Creating variables for all form element data
        String formEmail = regTxt1.getText();
        String formUser = regTxt2.getText();
        String formPass = new String((regTxt3.getPassword()));
        String formPass2 = new String((regTxt4.getPassword()));

        //Checking if data is blank
        if (!formEmail.equals("")) {
            //Checking if data is blank
            if (!formUser.equals("")) {
                //Checking if data is blank
                if (!formPass.equals("")) {
                    //Checking if data is blank
                    if (!formPass2.equals("")) {
                        //Comparing if both password match
                        if (formPass.equals(formPass2)) {
                            //Bolean creation for request to ended when user or email already exists
                            boolean isTaken = false;
                            //For loop through user array
                            for (int i = 0; i < sGP.userArray.size(); i++) {
                                //if username taken then boolean is set to true
                                if (sGP.userArray.get(i).user.equals(formUser)) {
                                    isTaken = true;
                                }
                            }
                            //Checking if user is taken
                            if (!isTaken) {
                                //Setting login entry object data to be added woth the array of users
                                loginElements lE = new loginElements();
                                lE.setUser(formUser);
                                lE.setEmail(formEmail);
                                lE.setPassword(formPass);
                                tmpArray.add(lE);
                                //Try-Catch statment with IOException used for file handling
                                try {
                                    //Calling upon constructor within the main class
                                    sGP.setArray(tmpArray);
                                } catch (IOException ex) {
                                    Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                //Confirmation message
                                registerErrorMsg.setText("Account created...");
                            } else {
                                //Error message
                                registerErrorMsg.setText("Username is already taken!");
                            }

                        } else {
                            //Error message
                            registerErrorMsg.setText("Both password fields need to match!");
                        }
                    } else {
                        //Error message
                        registerErrorMsg.setText("Please fill in the Password Retype field!");
                    }
                } else {
                    //Error message
                    registerErrorMsg.setText("Please fill in the the Password field!");
                }
            } else {
                //Error message
                registerErrorMsg.setText("Please fill in the Username field!");
            }
        } else {
            //Error message
            registerErrorMsg.setText("Please fill in the the Email field!");
        }
    }//GEN-LAST:event_regBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton regBtn;
    private javax.swing.JTextField regTxt1;
    private javax.swing.JTextField regTxt2;
    private javax.swing.JPasswordField regTxt3;
    private javax.swing.JPasswordField regTxt4;
    private javax.swing.JTextField registerErrorMsg;
    // End of variables declaration//GEN-END:variables
}
